# Generated by Django 5.0.6 on 2024-06-15 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interno', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nom',
            new_name='nome',
        ),
    ]
