# Generated by Django 5.0.6 on 2024-06-20 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interno', '0004_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45, unique=True)),
                ('quantidade', models.DecimalField(decimal_places=6, max_digits=40)),
                ('clima', models.TextField(max_length=40)),
                ('data', models.DateField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interno.estado')),
            ],
        ),
    ]
